name: scicomp_utils_dolfinx
channels:
  - conda-forge
  - defaults
dependencies: # pkg_name=version=build
  - petsc=3.*=complex*
  - petsc4py=3.*
  - mpich=4.2.*
  - fenics-dolfinx=0.8.*
  - dolfinx_mpc=0.8.*
  - libdolfinx_mpc=0.8.*
  - pytest=8.2.*
  - matplotlib=3.9.*
  - scipy=1.14.*
  - pyvista=0.36.1
  - pip=24.2
  - hatchling=1.25.0
  - editables=0.5
  - pip:
    - gmsh==4.12.*
    - -e . 