# This yml file provides a working environment without dolfinx_mpc.
name: dolfinx-0.5-complex
channels:
  - conda-forge
  - defaults
dependencies: # pkg_name=version=build
  - petsc=3.*=complex*
  - petsc4py
  - mpich
  - fenics-dolfinx=0.5.0
  - gmsh=4.9.3
  - python-gmsh=4.9.3
  - matplotlib
  - scipy
  - pip
  - pip:
    - hatchling
    - editables
    - scicomp_utils_mesh @ git+https://github.com/fmonteghetti/python-scientific-computing-utils/@main#subdirectory=scicomp_utils_mesh
    - scicomp_utils_misc @ git+https://github.com/fmonteghetti/python-scientific-computing-utils/@main#subdirectory=scicomp_utils_misc
    - pyvista
    - pybind11
    - . 