# The package `scicomp_utils_dolfinx` is installed in editable mode.
name: dolfinx-0.6-complex
channels:
  - conda-forge
  - defaults
dependencies: # pkg_name=version=build
  - petsc=3.*=complex*
  - petsc4py
  - mpich
  - fenics-dolfinx=0.6.0 # Also working: 0.7.1, 0.7.2, 0.7.3, 0.8.0
  - dolfinx_mpc
  - libdolfinx_mpc
  - gmsh
  - python-gmsh
  - matplotlib
  - scipy
  - pyvista=0.36.1
  - pip
  - pip:
    - hatchling
    - editables
    - scicomp_utils_mesh @ git+https://github.com/fmonteghetti/python-scientific-computing-utils/@main#subdirectory=scicomp_utils_mesh
    - scicomp_utils_misc @ git+https://github.com/fmonteghetti/python-scientific-computing-utils/@main#subdirectory=scicomp_utils_misc
    - pybind11
    - -e .
