name: scicomp_utils_dolfinx
channels:
  - conda-forge
  - defaults
dependencies: # pkg_name=version=build
  - petsc=3.*=complex*
  - petsc4py=3.19.*
  - mpich=4.2.*
  - fenics-dolfinx=0.6.0 # Also working: 0.7.1, 0.7.2, 0.7.3, 0.8.0
  - dolfinx_mpc=0.6.1
  - libdolfinx_mpc=0.6.1
  - pytest=8.2.*
  - matplotlib=3.9.*
  - scipy=1.14.*
  - pyvista=0.36.1
  - pip=24.2
  - hatchling=1.25.0
  - editables=0.5
  - pip:
    - gmsh==4.12.*
    - . 